---
language: node_js
node_js:
  - stable
cache:
  directories:
    - .meteor/local
    - node_modules
sudo: false

before_install:
  - 'curl https://install.meteor.com | /bin/sh'
  - export PATH="$HOME/.meteor:$PATH"
